services:
  - type: web
    name: vidsnapai-2ptc
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: PORT
        value: 3001
    healthCheckPath: /api/check
